package work.socialhub.kdiscord.entity

import kotlinx.serialization.Serializable
import kotlin.js.JsExport

/**
 * Discord message object.
 * https://discord.com/developers/docs/resources/message#message-object
 */
@JsExport
@Serializable
class Message {
    /** Id of the message (snowflake). */
    var id: String? = null

    /** Id of the channel the message was sent in (snowflake). */
    var channelId: String? = null

    /** The author of this message. */
    var author: User? = null

    /** Contents of the message. */
    var content: String? = null

    /** When this message was sent (ISO8601 timestamp). */
    var timestamp: String? = null

    /** When this message was edited (ISO8601 timestamp), or null if never. */
    var editedTimestamp: String? = null

    /** Whether this was a TTS message. */
    var tts: Boolean? = null

    /** Whether this message mentions everyone. */
    var mentionEveryone: Boolean? = null

    /** Users specifically mentioned in the message. */
    var mentions: Array<User>? = null

    /** Role ids specifically mentioned in this message (snowflakes). */
    var mentionRoles: Array<String>? = null

    /** Any attached files. */
    var attachments: Array<Attachment>? = null

    /** Any embedded content. */
    var embeds: Array<Embed>? = null

    /** Reactions to the message. */
    var reactions: Array<Reaction>? = null

    /** Whether this message is pinned. */
    var pinned: Boolean? = null

    /** If the message is generated by a webhook, this is the webhook's id (snowflake). */
    var webhookId: String? = null

    /** Type of message. */
    var type: Int? = null

    /** The id of the guild the message was sent in (snowflake). */
    var guildId: String? = null

    /** Member properties for this message's author. */
    var member: GuildMember? = null

    /** Reference data sent with crossposted messages and replies. */
    var messageReference: MessageReference? = null

    /** The message associated with the message_reference (for replies). */
    var referencedMessage: Message? = null

    /** A generally increasing integer that represents the approximate position in the thread. */
    var position: Int? = null
}

/**
 * Discord message reference object.
 * https://discord.com/developers/docs/resources/message#message-reference-structure
 */
@JsExport
@Serializable
class MessageReference {
    /** Type of reference. */
    var type: Int? = null

    /** Id of the originating message (snowflake). */
    var messageId: String? = null

    /** Id of the originating message's channel (snowflake). */
    var channelId: String? = null

    /** Id of the originating message's guild (snowflake). */
    var guildId: String? = null

    /** When sending, whether to error if the referenced message doesn't exist. */
    var failIfNotExists: Boolean? = null
}
